// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IArticleFields {
  /** Title */
  title?: string | undefined;

  /** Slug */
  slug?: string | undefined;

  /** Description */
  description?: string | undefined;

  /** Publish date */
  publishDate?: string | undefined;

  /** Content */
  content?: Document | undefined;
}

export interface IArticle extends Entry<IArticleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "article";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IComponentAuthorFields {
  /** Internal name */
  internalName: string;

  /** Name */
  name: string;

  /** Avatar */
  avatar?: Asset | undefined;
}

/** To have author-related properties */

export interface IComponentAuthor extends Entry<IComponentAuthorFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "componentAuthor";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IComponentRichImageFields {
  /** Internal name */
  internalName: string;

  /** Image */
  image: Asset;

  /** Caption */
  caption?: string | undefined;

  /** Full width */
  fullWidth?: boolean | undefined;
}

/** To describe an image used in rich text fields */

export interface IComponentRichImage extends Entry<IComponentRichImageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "componentRichImage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IComponentSeoFields {
  /** Internal name */
  internalName: string;

  /** Page title */
  pageTitle: string;

  /** Page description */
  pageDescription?: string | undefined;

  /** Canonical URL */
  canonicalUrl?: string | undefined;

  /** nofollow */
  nofollow: boolean;

  /** noindex */
  noindex: boolean;

  /** Share images */
  shareImages?: Asset[] | undefined;
}

/** To have SEO-related properties to the pages we render */

export interface IComponentSeo extends Entry<IComponentSeoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "componentSeo";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageBlogPostFields {
  /** Internal name */
  internalName: string;

  /** SEO fields */
  seoFields?: IComponentSeo | undefined;

  /** Slug */
  slug: string;

  /** Author */
  author?: IComponentAuthor | undefined;

  /** Published date */
  publishedDate: string;

  /** Title */
  title: string;

  /** Subtitle */
  shortDescription?: string | undefined;

  /** Featured image */
  featuredImage: Asset;

  /** Content */
  content: Document;

  /** Related blog posts */
  relatedBlogPosts?: IPageBlogPost[] | undefined;
}

/** To create individual blog posts */

export interface IPageBlogPost extends Entry<IPageBlogPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "pageBlogPost";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageLandingFields {
  /** Internal name */
  internalName: string;

  /** SEO fields */
  seoFields?: IComponentSeo | undefined;

  /** Featured blog post */
  featuredBlogPost?: IPageBlogPost | undefined;
}

/** To have an entry point for the app (e.g. Homepage) */

export interface IPageLanding extends Entry<IPageLandingFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "pageLanding";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "article"
  | "componentAuthor"
  | "componentRichImage"
  | "componentSeo"
  | "pageBlogPost"
  | "pageLanding";

export type IEntry =
  | IArticle
  | IComponentAuthor
  | IComponentRichImage
  | IComponentSeo
  | IPageBlogPost
  | IPageLanding;

export type LOCALE_CODE = "de-DE" | "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
